#!/usr/bin/env python3
from pathlib import Path
import json, subprocess

ROOT=Path.cwd(); PLAN=ROOT/'PLAN.md'; SNAP=ROOT/'research/game/snapshot.json'
EVID=ROOT/'research/evidence/2026-09-12-phase-graded-factor-two.md'

def replace_once(text,old,new,label):
    n=text.count(old)
    if n!=1: raise SystemExit(f'{label}: expected one site, found {n}')
    return text.replace(old,new,1)

def write_new(path,content):
    if path.exists() and path.read_text()!=content: raise SystemExit(f'refusing differing {path}')
    if not path.exists(): path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content)

def blob(path):
    return subprocess.run(['git','hash-object',str(path)],cwd=ROOT,text=True,capture_output=True,check=True).stdout.strip()

evidence=r'''# Physical phase grading separates the first factor-two relay from its cubic pollutant

Date: 2026-09-12. Repository input before integration: current `main`.

**Status: exact lattice/phase theorem and recursive-degree obstruction; independent mathematical audit and novelty assessment pending.** The existing complete Taylor relay and cubic-pollution coefficients are not recomputed here. This packet identifies their exact physical phase grades and proves a separate obstruction to treating an infinite relay as one fixed small-data Taylor expansion.

## 1. Prediction before the test

The source's physical harmonic-protection theorem says linear physical corrections preserve a phase integer and products add phase integers. The four positive parent frequencies in the frozen cage all carry the same phase integer `m`, while their reality partners carry `-m`.

Prediction: the unavoidable cubic pollutant and the desired doubled parents occupy different physical phase grades. If so, the cubic term does not directly cancel the first doubled-parent coefficient, although it remains an inherited unstable degree of freedom after rescaling.

## 2. The phase grade is exactly the lattice `z` coordinate

The four positive parent lattice keys are

    (5,1), (-4,1), (2,1), (-1,1),                       (2.1)

and their reality partners are the negatives. Assign physical grade `+1` to the positive parents and `-1` to their partners, in units of `m`.

Every source-reference linear term preserves the Fourier key. The physical slow/background/mean, diffusion, pressure-reconstruction and localization terms covered by the existing harmonic-protection theorem preserve the phase integer. Quadratic convolution adds Fourier keys and adds phase integers.

Therefore the two additive homomorphisms agree on the generators and hence on the whole algebra generated by them:

    physical phase grade / m = z.                        (2.2)

This is exact. It is not an asymptotic finite-`L` statement.

## 3. First relay and pollutant are in different grades

The frozen cubic-pollution theorem isolates the extreme sideband

    (14,1)= (5,1)+(5,1)-(-4,1).                           (3.1)

By (2.2) it lies in physical phase grade `m`. Its cubic ancestry is `m+m-m=m`.

The complete factor-two relay theorem proves nonzero growing-branch coefficients at

    (10,2), (-8,2), (4,2), (-2,2).                       (3.2)

All four lie in physical phase grade `2m`. The transparent relay subtree has the same bookkeeping: the common daughter has grade `m+m=2m`; each pair-difference shear has grade `m-m=0`; daughter plus shear remains grade `2m`.

Consequently the unavoidable cubic grade-`m` pollutant cannot algebraically cancel the already proved first grade-`2m` doubled-parent coefficients. The first factor-two relay survives this particular pollution objection.

This does **not** remove the pollutant. Under factor-two normalization the `(14,1)` mode becomes linearly unstable one nonlinear order earlier than the desired quartic relay, and the number of inherited unstable sites grows without bound. Phase separation is triangular bookkeeping, not a finite-dimensional closure.

## 4. Exact degree/grade ancestry obstruction

Start from factors of grade `+m` and `-m`. A monomial of amplitude degree `d` has grade `q m` exactly when

    |q| <= d,          d-q is even.                       (4.1)

Proof. If `p` positive-grade and `r` negative-grade factors occur, then `p+r=d` and `p-r=q`, so `p=(d+q)/2`, `r=(d-q)/2`. Nonnegative integral `p,r` are equivalent to (4.1).

In particular a descendant of grade

    2^j m                                                   (4.2)

cannot occur below amplitude degree `2^j` in a Taylor expansion about the original parents.

Hence no **fixed finite Taylor order** in the original small four-parent seed can realize arbitrary relay depth. A recursive construction must contain a genuine stagewise amplification/renormalization mechanism: a generated grade must become a new order-one stage variable before it can feed the next doubling at controlled order. Concatenating local coefficients without such gain is not a cascade proof.

## 5. Recomputed constructive frontier

The phase grading sharpens but does not close UE1. The first doubled-parent birth is algebraically protected from the known cubic pollutant, while the pollutant persists in a lower grade and joins the expanding unstable state.

A surviving nonlinear construction therefore needs a finite-duration **stage map** for the full returned state, not another selected Fourier tree or finite Taylor jet. It must amplify/renormalize the grade-`2^j m` parent sector while controlling all inherited lower grades, localization, pressure, and ordinary diffusion. The existing finite-`L` theorem provides only one fixed local fast-time window and does not supply this interstage map.

The competing routes remain sparse/nonlocal thin-collar entry and the complete physical adjoint. No common Schwartz trace, full nonlinear de-forcing solution, singularity preservation or `NS-R3` conclusion is claimed.

`research/check_phase_graded_factor_two.py` freezes the exact homomorphism and degree/grade arithmetic. The actual nonzero relay and pollutant coefficients remain those of the already frozen complete checkers.
'''
write_new(EVID,evidence)

plan=PLAN.read_text()
plan=replace_once(plan,
    'source_correction_conveyor_scaling: energy-compatible-but-nondegenerate-conveyor-terminal-strength\nsource_global_growing_parent_supply: not-produced',
    'source_correction_conveyor_scaling: energy-compatible-but-nondegenerate-conveyor-terminal-strength\nsource_phase_graded_relay: first-doubling-separated-from-cubic-pollutant-fixed-order-infinite-relay-impossible\nsource_global_growing_parent_supply: not-produced',
    'PLAN yaml phase status')
old='''The next active test must therefore address sparse correction-driven thin-collar
entry or in-core nonlinear generation with the inherited angular hierarchy
retained, or estimate the complete physical adjoint including those mechanisms.
No bound on the sparse collar stress or full-history gain has been obtained;
direct far-field quadratic pressure input has the energy-only bound above. UE1
and the terminal claim remain open.
'''
new='''The factor-two nonlinear branch has one additional exact triangular structure.
On the algebra generated by the four positive parents and their reality
partners, the physical phase grade in units of the common parent integer `m`
is exactly the lattice `z` coordinate. Hence the unavoidable cubic pollutant
`(14,1)` is grade `m`, while the already proved doubled parents `(*,2)` are
grade `2m`; the pollutant cannot directly cancel the first doubled-parent
coefficients. However a degree-`d` monomial in the original `+/-m` factors can
have grade `q m` only when `|q|<=d` and `d-q` is even. Thus grade `2^j m`
requires degree at least `2^j`: no fixed finite Taylor expansion is an infinite
relay. A viable cascade now needs a genuine finite-duration stagewise
amplification/renormalization map for the full expanding returned state. See
`research/evidence/2026-09-12-phase-graded-factor-two.md`.

The next active test must therefore address that stagewise interstage map,
sparse correction-driven thin-collar/nonlocal entry, or the complete physical
adjoint including those mechanisms. No bound on the sparse collar stress or
full-history gain has been obtained; direct far-field quadratic pressure input
has the energy-only bound above. UE1 and the terminal claim remain open.
'''
plan=replace_once(plan,old,new,'PLAN frontier phase paragraph')
PLAN.write_text(plan)

snap=json.loads(SNAP.read_text())
snap['authoritative_sources']['PLAN.md']=blob(PLAN)
snap['authoritative_sources'][str(EVID.relative_to(ROOT))]=blob(EVID)
snap['active_frontier']='finite-duration stagewise nonlinear amplification/renormalization of the expanding phase-graded parent state, sparse thin-collar/nonlocal entry, or a complete physical adjoint with whole-prehistory cost control'
SNAP.write_text(json.dumps(snap,indent=2)+'\n')
print('prepared phase-graded relay checkpoint')
