KNOWN={
    'terminal-open': {'terminal_status': 'not-proved', 'unforced_counterexample': 'not-constructed'},
    'positive-consumer': {'needs': 'input-only arbitrary-data critical producer', 'consumer': 'finite L^{3,q} or equivalent continuation bound'},
    'finite-inverse-scope': {'finite_horizon_inverse': True, 'common_physical_trace': False, 'endpoint_uniformity': False},
    'all-penalty-selector': {'all_nonnegative_penalties': True, 'operator_lipschitz_in_history': True, 'source_endpoint_control': False},
    'common-control-criterion': {'common_finite_norm_control_iff': 'uniformly bounded minimum-norm prefix controls', 'source_passes_test': False},
    'source-local-entry-seed': {'entry_seed_cost': 'comparable to P(0)=exp(-gamma_- L)', 'peak_preserved_locally': True, 'one_global_initial_trace': False},
    'source-covariance-retuning': {'positive_weights_preserved': True, 'relative_change': 'O(sqrt(L) exp(-c L))', 'full_mean_pressure_repaired': False},
    'source-zero-extension-gluing': {'unforced_full_NS_gluing': False, 'obstruction': 'nonzero solenoidal temporal delta impulses'},
    'localized-adjoint-shortcut': {'zero_initial_trace_cutoff_adjoint_valid': False, 'defect_pairing': 'exact half-unit cancellation'},
    'angular-homogeneous-preparation': {'trapped_homogeneous_preparation': 'superalgebraically damped', 'surviving_alternatives': 'radial exterior occupation or large nonlinear supply'},
    'angular-resonance-budget': {'input_only_weighted_moment_budget': True, 'thin_resonance_slab_cost': 'O(eta)', 'RFq_producer': False},
    'comparable-normal-form-wall': {'boundary_primitive_over_entropy': 'M/(nu eta)', 'uniform_arbitrary_amplitude_coercivity': False},
    'raman-simultaneous-ordering': {'claimed_leading_one_order_transfer_survives_full_time_ordering': False},
    'raman-dynamic-parent-birth': {'complete_O_N_target_response': 'zero', 'active_terminal_route': False},
    'source-spectral-cage': {'unstable_positive_sites': 'exactly four parent sites plus reality partners', 'stable_complement_margin': 'uniform negative'},
    'source-reference-unstable-manifold': {'full_lattice_causal_prehistory': True, 'pure_decaying_target_generated': True, 'stable_modes_reset': False},
    'source-finite-L-cage': {'rank_two_lattice_persists': True, 'fixed_window_full_lattice_retuning': True, 'global_parent_supply': False},
    'source-correlated-rounding': {'two_pair_daughter_index_can_match_exactly': True, 'forced_fourth_rounding_error': 'bounded by 3/2'},
    'source-harmonic-protection': {'linear_O_epsilon_over_L_daughter_leakage': False, 'first_physical_daughter_error': 'O(epsilon^2/L)+O(epsilon^3)', 'global_parent_supply': False},
    'numerics-not-certificate': {'numerical_orbit_proves_blowup': False, 'numerical_orbit_proves_regularity': False},
    'exterior-pressure-transmission': {'norm_attenuation': '(r/R)^abs(n)', 'bounded_budget_import': 'requires thin collar or fails entry scale', 'complete_physical_adjoint': False},
    'clock-action-obstruction': {'fixed_action_requires': 'S/N^2 >= c0', 'slow_purifier_requires': 'lambda*b >= eta0', 'bounded_fast_parent_requires': 'lambda*sqrt(S) <= C0', 'all_three_with_N_over_b_to_infinity': False},
    'old-strong-scaling-action': {'integrated_clean_action_limit': 0, 'sufficient_for_fixed_positive_filter_action': False},
}
def predict(control): return KNOWN[control['id']]
