KNOWN={
    'terminal-open': {'terminal_status': 'not-proved', 'unforced_counterexample': 'not-constructed'},
    'positive-consumer': {'needs': 'input-only arbitrary-data critical producer', 'consumer': 'finite L^{3,q} or equivalent continuation bound'},
    'finite-inverse-scope': {'finite_horizon_inverse': True, 'common_physical_trace': False, 'endpoint_uniformity': False},
    'all-penalty-selector': {'all_nonnegative_penalties': True, 'operator_lipschitz_in_history': True, 'source_endpoint_control': False},
    'common-control-criterion': {'common_finite_norm_control_iff': 'uniformly bounded minimum-norm prefix controls', 'source_passes_test': False},
    'source-local-entry-seed': {'entry_seed_cost': 'comparable to P(0)=exp(-gamma_- L)', 'peak_preserved_locally': True, 'one_global_initial_trace': False},
    'source-covariance-retuning': {'positive_weights_preserved': True, 'relative_change': 'O(sqrt(L) exp(-c L))', 'full_mean_pressure_repaired': False},
    'source-zero-extension-gluing': {'unforced_full_NS_gluing': False, 'obstruction': 'nonzero solenoidal temporal delta impulses'},
    'localized-adjoint-shortcut': {'zero_initial_trace_cutoff_adjoint_valid': False, 'defect_pairing': 'exact half-unit cancellation'},
    'angular-homogeneous-preparation': {'trapped_homogeneous_preparation': 'superalgebraically damped', 'surviving_alternatives': 'radial exterior occupation or large nonlinear supply'},
    'angular-resonance-budget': {'input_only_weighted_moment_budget': True, 'thin_resonance_slab_cost': 'O(eta)', 'RFq_producer': False},
    'comparable-normal-form-wall': {'boundary_primitive_over_entropy': 'M/(nu eta)', 'uniform_arbitrary_amplitude_coercivity': False},
    'raman-simultaneous-ordering': {'claimed_leading_one_order_transfer_survives_full_time_ordering': False},
    'raman-dynamic-parent-birth': {'complete_O_N_target_response': 'zero', 'active_terminal_route': False},
    'source-spectral-cage': {'unstable_positive_sites': 'exactly four parent sites plus reality partners', 'stable_complement_margin': 'uniform negative'},
    'source-reference-unstable-manifold': {'full_lattice_causal_prehistory': True, 'pure_decaying_target_generated': True, 'stable_modes_reset': False},
    'source-finite-L-cage': {'rank_two_lattice_persists': True, 'fixed_window_full_lattice_retuning': True, 'global_parent_supply': False},
    'source-correlated-rounding': {'two_pair_daughter_index_can_match_exactly': True, 'forced_fourth_rounding_error': 'bounded by 3/2'},
    'source-harmonic-protection': {'linear_O_epsilon_over_L_daughter_leakage': False, 'first_physical_daughter_error': 'O(epsilon^2/L)+O(epsilon^3)', 'global_parent_supply': False},
    'numerics-not-certificate': {'numerical_orbit_proves_blowup': False, 'numerical_orbit_proves_regularity': False},
    'exterior-pressure-transmission': {'norm_attenuation': '(r/R)^abs(n)', 'bounded_budget_import': 'requires thin collar or fails entry scale', 'complete_physical_adjoint': False},
    'clock-action-obstruction': {'fixed_action_requires': 'S/N^2 >= c0', 'slow_purifier_requires': 'lambda*b >= eta0', 'bounded_fast_parent_requires': 'lambda*sqrt(S) <= C0', 'all_three_with_N_over_b_to_infinity': False},
    'old-strong-scaling-action': {'integrated_clean_action_limit': 0, 'sufficient_for_fixed_positive_filter_action': False},
    'energy-controlled-exterior-pressure': {'L1_stress_to_L2_constant': '3/sqrt(2*pi)', 'optimal_intermediate_radius': '2*N*R/(2*N+5)', 'quadratic_far_input': 'bounded by initial energy', 'full_history_gain': False},
    'relay-scale-homogeneity': {'hard_targets': '2p1,2p2 quadratic-zero quartic-nonzero', 'easy_targets': '2p3,2p4 quadratic-nonzero', 'factor_two_scale': 'hard=1/8 easy=1/2', 'finite_duration_stage_map': False},
    'stage-balance-wall': {'easy_product': 'nonzero fixed multiple of epsilon^4', 'balanced_parent_easy_lower_bound': 'at least one Omega(epsilon^2)', 'hard_birth_order': 'O(epsilon^4)', 'linear_rate_order': 'every easy rate exceeds every hard rate', 'birth_then_linear_balance': False},
    'stable-preload-balance': {'easy_leading_births_cancelled': True, 'lower_order_hard_contamination': False, 'corrected_hard_coefficients_nonzero': True, 'exact_short_stage_easy_retuning': True, 'recursive_counterterm_supply': False},
    'counterterm-causal-mismatch': {'unstable_manifold_quadratic_coordinate': 'F/D', 'future_canceling_coordinate': '-F*(exp(D*T)-1)/D', 'ratio_for_T_positive': '1-exp(D*T)<0', 'four_parent_causal_counterterm_supply': False},
    'single-label-interstage-wall': {'same_label_fast_displacement_over_L': 'diverges like Q^(-h)/ell^2', 'parent_relative_lattice_deformation_lower_bound': 'sqrt(9/500)*abs(Delta v/L)', 'direct_fixed_label_adapter': False, 'recentered_multilabel_adapter': 'open'},
    'recenter-cage-wall': {'same_rational_cage_after_forward_shift': False, 'same_cage_multiset_condition': 'a=1', 'outer_parent_stable_by_multiplier': 'a>=13/9', 'general_grade_changing_adapter': 'open'},
    'sparse-collar-l3-threshold': {'required_energy_exponent': '-(C-kappa/2) for kappa<2C', 'forced_L3_exponent': '-(C-kappa/2)/2+beta/6', 'L3_growth_threshold': 'beta>3(C-kappa/2)', 'sparse_support_alone_excludes_collar': False, 'quadratic_stress_attainability': 'open'},
    'collar-angular-ancestry': {'low_low_target_grade': False, 'required_velocity_ancestor': 'abs(m)>=N/2', 'target_stress_bound': '2 ||u_H||_2 ||u||_2', 'universal_divergence_free_pressure_cancellation': False, 'collar_parent_supply': 'relocated-to-high-grade-ancestry'},
    'adjoint-strain-sign-wall': {'solenoidal_strain_trace': 0, 'nonzero_strain_pointwise_indefinite': True, 'zero_strain_L2_solenoidal_adjoint': 'zero', 'sign_only_nonlinear_certificate': False},
    'adjoint-principal-stress-dual': {'symmetric_inverse_divergence': 'Ghat=-i(k⊗f+f⊗k)/|k|^2', 'stress_norm': 'sqrt(2)|f|/|k|', 'pairs_with_symmetric_strain': True, 'principal_high_frequency_adjoint_obstruction': False},
    'half-grade-parent-carry-wall': {'parent_reference_exponent_bracket': '>9/10', 'parent_carry_gain': 'exp(+c Q^(-h))', 'Qminus_h_over_L': 'diverges for L~ell^2', 'passive_small_data_parent_reuse': False, 'late_nonlinear_regeneration': 'open'},
    'half-grade-six-mode-bridge': {'half_grade_ancestors': '14,-13,5,-4,2,-1 all positive-branch growing', 'cubic_extremes': 'both +14 and -13 nonzero unique monomials', 'next_parent_quadratic_edges': 'all four nonzero', 'leading_target_rank': 4, 'finite_duration_bridge': 'open', 'late_causal_six_mode_supply': False},
    'half-grade-finite-time-bridge': {'quadratic_competitors': 'only self pairs, identically zero', 'four_growth_mismatches': 'strictly positive', 'finite_time_target_rank': 4, 'full_infinite_lattice_retuning': True, 'late_causal_six_mode_supply': False, 'physical_finite_L_lift': False},
}
def predict(control): return KNOWN[control['id']]
